GET http://localhost:3000/users

###

GET http://localhost:3000/users/60848e0d71b13c3308275472
###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name" : "Payal", 
    "userInteraction" :"Hello There"
    
}


###

DELETE http://localhost:3000/users/5ff49a79f03c9355944729c3

###

PATCH  http://localhost:3000/users/5ff495855f18d234d4913961
Content-Type: application/json

{
    "name" : "Payal"
}